version: '3'
services:
  database:
    container_name: database
    image: postgres:12
    volumes:
      - directus-db:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  directus:
    container_name: directus
    # image: directus/directus:9.0.0-rc.91
    image: directus/directus:9.14
    ports:
      - 8055:8055
    restart: on-failure
    volumes:
      - ./prom-metrics:/directus/extensions/hooks/prom-metrics
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'

      EXTENSIONS_AUTO_RELOAD: 'true'
      # LOG_LEVEL: "trace"
      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      PUBLIC_URL: 'http://localhost:8055'


networks:
  directus:

volumes:
  directus-db:
